theme: jekyll-theme-minimal

logo: img/logo.png
description: [Base de datos que incluye mujeres lesbianas trans intersex personas de género fluido y otras disidencias que experimentan con sonido en Latinoamérica]
